### ISSUE TITLE
mockup API 기능을 추가하기

### ISSUE THREAD

**Issue by Malloc72P** [Malloc72P/todo-list#3]
프론트 분들이 개발하면서 필요한 mockup API를 빨리 만들어야 한다

**Comment by deprecated-hongbiii** [comment]
천천히 해주셔도 됩니당 ☺️ ㅋㅋㅋㅋㅋ 저희가 느려서.. 호호

**Comment by Malloc72P** [comment]
> 천천히 해주셔도 됩니당 ☺️ ㅋㅋㅋㅋㅋ 저희가 느려서.. 호호

ㅎㅎ 알겠습니당
