### ISSUE TITLE
브랜치 제안

### ISSUE THREAD

**Issue by deprecated-hongbiii** [Malloc72P/todo-list#9]
Dev 브랜치를 사용하는 것을 제안합니다.

https://github.com/elsewhencode/project-guidelines/blob/master/README-ko.md

**Comment by Malloc72P** [comment]
저도 그 방법이 좋은 것 같아요! dev브랜치 생성해두었습니다! 
나중에 병합할때 쓰면 좋을 것 같네요! `╰(*°▽°*)╯`
